### ISSUE TITLE
Not able to sort cursor

### ISSUE THREAD

**Issue by eposschweiz** [peterclark/tinymodel#1]
Hi

I can not sort the cursor.

Project.all( {}, {sort: { property: -1 }}
Project.find( {}, {sort: { property: -1 }}

both aren't working. the sortorder don't changes

**Comment by peterclark** [comment]
Thanks @eposschweiz, I'll take a look.

**Comment by eposschweiz** [comment]
nice. thanks!

Lukas

**Comment by eposschweiz** [comment]
that was pretty fast :-)

**Comment by peterclark** [comment]
thanks for catching the bug!
